In [4]:
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print s

0    a
1    b
2    c
3    d
dtype: object


In [5]:
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s= pd.Series(data,index=[100,101,102,103])
print s

100    a
101    b
102    c
103    d
dtype: object


In [7]:
import pandas as dp
import numpy as np
data ={'a':1,'b':2,'c':3,'d':4}
s=pd.Series(data)
print s

a    1
b    2
c    3
d    4
dtype: int64


In [8]:
import pandas as pd
import numpy as np
d=pd.Series([1,2,3,3,4,5,5,6],index=['a','b','c','d','e','f','g','h'])
d

a    1
b    2
c    3
d    3
e    4
f    5
g    5
h    6
dtype: int64

In [ ]:
# data frames

In [10]:
import pandas as pd
d=[1,2,3,4,5,6,7]
s=pd.DataFrame(d)
print s

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7


In [12]:
import pandas as pd
data=[['rama',1],['krishna',2],['vishnu',3]]
s=pd.DataFrame(data,columns=['name','Rank'])
print s

      name  Rank
0     rama     1
1  krishna     2
2   vishnu     3


In [13]:
import pandas as pd
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],
'Age':[28,34,29,42]}
df= pd.DataFrame(data)

In [14]:
df

Age   Name
0   28    Tom
1   34   Jack
2   29  Steve
3   42  Ricky

In [15]:
import pandas as pd
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
print df ['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64


In [16]:
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [17]:
import pandas as pd
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
# Adding a new column to an existing DataFrame object with column label by passing new series
print ("Adding a new column by passing as Series:")
df['three']=pd.Series([10,20,30],index=['a','b','c'])
print df
print ("Adding a new column using the existing columns in DataFrame:")
df['four']=df['one']+df['three']
print df

Adding a new column by passing as Series:
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
Adding a new column using the existing columns in DataFrame:
   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN


In [20]:
import pandas as pd
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
print df.loc['b']

one    2.0
two    2.0
Name: b, dtype: float64


In [21]:
import pandas as pd
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
print df.iloc[2]

one    3.0
two    3.0
Name: c, dtype: float64


In [22]:
import pandas as pd
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
print df[2:4]

   one  two
c  3.0    3
d  NaN    4


In [23]:
import pandas as pd
df = pd.DataFrame([[1, 2], [3, 4]], columns=['a','b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=['a','b'])
df = df.append(df2)
print df

   a  b
0  1  2
1  3  4
0  5  6
1  7  8


In [24]:
np.random.randn(4
            , 3)

array([[-0.86213391,  0.15517804, -0.29043622],
       [-0.08321166,  0.29228401, -1.04762291],
       [ 1.27140675, -0.18111412, -0.91206902],
       [-0.75642564,  1.07631761, -0.78874323]])

In [25]:
np.random.randn(4, 3)),

SyntaxError: invalid syntax (<ipython-input-25-cfe771b0586e>, line 1)

In [26]:
np.random.randn(4, 3)

array([[ 0.29575025,  0.00533411,  0.07425925],
       [-0.9112612 ,  0.92078014, -1.13881525],
       [ 0.51561964, -1.06659019, -0.93758827],
       [-0.40433947,  0.90739924,  0.77037755]])

In [27]:
np.random.randn(7, 7)

array([[-0.53142666, -1.25822551, -1.03462354, -0.1866517 , -2.04816667,
        -0.58990465, -1.67348342],
       [-0.03432551,  0.23598438, -1.14115783,  0.7473988 ,  0.4578965 ,
         1.50805647, -1.74030912],
       [ 1.21585047,  0.21429501,  1.67210342, -1.22153677, -0.55015752,
         0.99783084,  0.34303722],
       [ 3.32738391,  1.41593395,  0.23473033,  0.72972289,  0.83000611,
        -1.03221497,  1.43520703],
       [ 0.1850032 , -0.74706195, -0.42674185,  1.56200345,  0.06355806,
        -1.08604496, -1.41093891],
       [-0.24778558, -0.23990755,  1.42280094,  0.51793922, -0.07865949,
         0.72579076, -0.48001191],
       [ 0.34805764, -0.43100299, -1.39599415,  0.48997217, -1.1159468 ,
        -0.91518296,  0.19562754]])

In [32]:
# creating an empty panel
import pandas as pd
import numpy as np
data = {'Item1' : pd.DataFrame(np.random.randn(4, 3)),
'Item2' : pd.DataFrame(np.random.randn(4, 2))}
p = pd.Panel(data)
print p['Item2']
print p['Item1']

          0         1   2
0 -1.041750  1.164979 NaN
1 -2.451518 -1.079969 NaN
2 -0.746519 -1.350490 NaN
3 -0.762291  0.373828 NaN
          0         1         2
0 -2.014721 -0.314634 -0.567295
1  0.476593 -0.882411  0.841274
2  1.344765  1.802420 -0.860154
3  0.295307 -0.031164 -0.228031


In [33]:
print p.major_xs(1)

      Item1     Item2
0  0.476593 -2.451518
1 -0.882411 -1.079969
2  0.841274       NaN


In [34]:
# creating an empty panel
import pandas as pd
import numpy as np
data = {'Item1' : pd.DataFrame(np.random.randn(4, 3)),
'Item2' : pd.DataFrame(np.random.randn(4, 2))}
p = pd.Panel(data)
print p.minor_xs(1)

      Item1     Item2
0  0.191617  1.724110
1 -1.498120  0.115775
2  0.666731  0.064415
3  0.867600  0.108967
